language: go

go:
  - 1.13.x

services:
  - mysql
  - redis-server

install:
  - go mod download
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - cd handlers
  - go test -v -covermode=count -coverprofile=coverage.out
  - cd ..
  - go build
